### ISSUE TITLE
Menu and Main view

### ISSUE THREAD

**Issue by makara-deu** [pnc-virtual-company/2020-G5-LMS#12]
The menu stand at the header and it will contain list : 
- Your leaves 
- Lear requests
- Employees 
- Positions 
- Departments 
- Combo-box (For display the firstname as uppercase of 
   user and it can show 
   the profile picture and logout)

**Comment by sopheaktraros** [comment]
@channakchhon Good afternoon teacher! please help with the main view and menu.
