### ISSUE TITLE
TASK 13 : Active status process

### ISSUE THREAD

**Issue by makara-deu** [pnc-virtual-company/2020-G5-LMS#8]
-When employee is ACTIVE, a Deactivate button shall be displayed on hover
- The value of Active is integer (1) will store into users table in the status field.

**Comment by channakchhon** [comment]
There is no design mockup.
All you need to do is to create view(blade) or HTML CSS

**Comment by makara-deu** [comment]
This task had already fix with update view in the manage_inactive_employee branch
