### ISSUE TITLE
All Database tables

### ISSUE THREAD

**Issue by makara-deu** [pnc-virtual-company/2020-G5-LMS#9]
In this task need to complete as : 
- Design database (paper + mysqlwordbank )
- Create all table that required 
  (departments,positions,employees........)
- Create database (Using migration)

**Comment by makara-deu** [comment]
![lmsdatabase](https://user-images.githubusercontent.com/58509047/87016166-8b386300-c1f8-11ea-8850-32577499421f.png)

**Comment by makara-deu** [comment]
This is our database design

**Comment by makara-deu** [comment]
We need teacher to verify this task @channakchhon

**Comment by makara-deu** [comment]
![updatelmsdabase](https://user-images.githubusercontent.com/58509047/87035139-1888b100-c213-11ea-8171-87940013d279.png)

**Comment by channakchhon** [comment]
You can't close issue.
Only Project Manager

**Comment by makara-deu** [comment]
Some issue I nee to delete but I can't because I don't have this permission, so I want teacher delete some issue that I confuse to create like : TAST 1, TASK2 ,TASK 3, TASK 4 , Design logo and mouckup . 
@channakchhon @raiya123 @radytrainer
